#!/usr/bin/env python3
"""P0-3: Build canonical manifest from Pilot-14 output and generate LaTeX macros.

Walks sgsc_output/ directory, builds a BenchmarkManifest via build_manifest(),
generates paper-ready LaTeX macros, and verifies self-consistency.

Usage:
    PYTHONPATH=. python scripts/sgsc/build_manifest_tables.py
    PYTHONPATH=. python scripts/sgsc/build_manifest_tables.py --models 8 --runs 3
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
from pathlib import Path
import subprocess
import sys

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
if str(REPO_ROOT.parent) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT.parent))

from sgsc.manifest import (  # noqa: E402
    build_manifest,
    load_manifest,
    manifest_to_dict,
    verify_manifest,
)

logger = logging.getLogger("build_manifest_tables")


def _git_commit() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=str(REPO_ROOT), text=True).strip()
    except Exception:
        return "unknown"


def collect_scenario_counts(sgsc_dir: Path) -> dict[str, int]:
    """Count public/private/total scenarios across all guidelines."""
    public_count = 0
    private_count = 0

    for guideline_dir in sorted(sgsc_dir.iterdir()):
        if not guideline_dir.is_dir():
            continue

        for pub_file in guideline_dir.glob("*_scenarios_public.json"):
            try:
                data = json.loads(pub_file.read_text())
                if isinstance(data, dict):
                    public_count += len(data)
            except (json.JSONDecodeError, OSError):
                pass

        for priv_file in guideline_dir.glob("*_scenarios_private.json"):
            try:
                data = json.loads(priv_file.read_text())
                if isinstance(data, dict):
                    private_count += len(data)
            except (json.JSONDecodeError, OSError):
                pass

    return {
        "public": public_count,
        "private": private_count,
        "manual": 0,
        "auto": public_count,
    }


def collect_atom_stats(sgsc_dir: Path) -> dict[str, int]:
    """Count atoms and constraint types across all guidelines."""
    total_atoms = 0
    constraint_types: dict[str, int] = {}

    for guideline_dir in sorted(sgsc_dir.iterdir()):
        if not guideline_dir.is_dir():
            continue

        for atom_file in guideline_dir.glob("atoms_smoke.json"):
            try:
                data = json.loads(atom_file.read_text())
                if isinstance(data, list):
                    total_atoms += len(data)
                    for atom in data:
                        if isinstance(atom, dict):
                            ctype = atom.get("constraint", {}).get("type", "UNKNOWN")
                            constraint_types[ctype] = constraint_types.get(ctype, 0) + 1
            except (json.JSONDecodeError, OSError):
                pass

    return {"total_atoms": total_atoms, "constraint_types": constraint_types}


def collect_artifact_names(sgsc_dir: Path) -> list[str]:
    """Collect hashable artifact filenames."""
    names: list[str] = []
    for guideline_dir in sorted(sgsc_dir.iterdir()):
        if not guideline_dir.is_dir():
            continue
        for f in sorted(guideline_dir.iterdir()):
            if f.suffix == ".json":
                names.append(str(f.relative_to(sgsc_dir)))
    # Also include the pilot report
    report = sgsc_dir / "pilot_14_report.json"
    if report.exists():
        names.append("pilot_14_report.json")
    return names


def generate_latex_macros(
    scenario_counts: dict[str, int],
    atom_stats: dict,
    episode_formula: dict[str, int],
    guidelines_count: int,
) -> str:
    """Generate LaTeX macro definitions for the paper."""
    lines = [
        "% Auto-generated SGSC manifest macros",
        f"% Generated by build_manifest_tables.py at commit {_git_commit()[:8]}",
        "",
        f"\\providecommand{{\\sgscGuidelineCount}}{{{guidelines_count}}}",
        f"\\providecommand{{\\sgscScenarioCount}}{{{scenario_counts['public']}}}",
        f"\\providecommand{{\\sgscAtomCount}}{{{atom_stats['total_atoms']}}}",
        f"\\providecommand{{\\sgscModelCount}}{{{episode_formula['models']}}}",
        f"\\providecommand{{\\sgscRunCount}}{{{episode_formula['runs']}}}",
        f"\\providecommand{{\\sgscExpectedEpisodes}}{{{episode_formula['expected_episodes']}}}",
    ]

    # Constraint type macros
    for ctype, count in sorted(atom_stats.get("constraint_types", {}).items()):
        safe_name = ctype.replace("_", "").capitalize()
        lines.append(f"\\providecommand{{\\sgscConstraint{safe_name}}}{{{count}}}")

    lines.append("")
    return "\n".join(lines)


def check_drift(
    sgsc_dir: Path,
    previous_path: Path | None,
) -> list[str]:
    """Compare current manifest against a previous one for drift."""
    if not previous_path or not previous_path.exists():
        return []

    try:
        prev_manifest = load_manifest(previous_path)
    except Exception as e:
        return [f"Failed to load previous manifest: {e}"]

    _ok, mismatches = verify_manifest(prev_manifest, sgsc_dir)
    return mismatches


def run_build(
    sgsc_dir: Path,
    models: int,
    runs: int,
    previous_manifest: Path | None,
) -> tuple[dict, dict, str]:
    """Build manifest and return (manifest_dict, report, latex_macros)."""
    # Count guidelines
    guideline_dirs = [d for d in sgsc_dir.iterdir() if d.is_dir()]
    guidelines_count = len(guideline_dirs)

    # Collect counts
    scenario_counts = collect_scenario_counts(sgsc_dir)
    atom_stats = collect_atom_stats(sgsc_dir)
    artifact_names = collect_artifact_names(sgsc_dir)

    total_scenarios = scenario_counts["public"]
    episode_formula = {
        "models": models,
        "scenarios": total_scenarios,
        "runs": runs,
        "expected_episodes": models * total_scenarios * runs,
    }

    # Build manifest
    manifest = build_manifest(
        benchmark_version="sgsc_v1",
        scenario_count=scenario_counts,
        episode_formula=episode_formula,
        artifacts_dir=sgsc_dir,
        artifact_names=artifact_names,
    )

    manifest_dict = manifest_to_dict(manifest)
    manifest_dict["extended"] = {
        "guidelines_count": guidelines_count,
        "atom_count": atom_stats["total_atoms"],
        "constraint_types": atom_stats.get("constraint_types", {}),
    }

    # Drift check
    drift = check_drift(sgsc_dir, previous_manifest)

    # LaTeX macros
    latex = generate_latex_macros(scenario_counts, atom_stats, episode_formula, guidelines_count)

    # Build check report
    failures: list[dict] = []
    status = "pass"

    if drift:
        status = "warn"
        for d in drift:
            failures.append({"check": "drift", "detail": d})

    report = {
        "check_name": "manifest_build",
        "status": status,
        "commit": _git_commit(),
        "input_hash": hashlib.sha256(json.dumps(artifact_names, sort_keys=True).encode()).hexdigest(),
        "metrics": {
            "guidelines_count": guidelines_count,
            "scenario_count": scenario_counts,
            "total_atoms": atom_stats["total_atoms"],
            "constraint_types": atom_stats.get("constraint_types", {}),
            "episode_formula": episode_formula,
            "artifact_count": len(manifest.artifact_hashes),
            "drift_count": len(drift),
        },
        "failures": failures,
    }

    report_bytes = json.dumps(report, sort_keys=True).encode()
    report["output_hash"] = hashlib.sha256(report_bytes).hexdigest()

    return manifest_dict, report, latex


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="P0-3: Build manifest tables")
    parser.add_argument("--sgsc-dir", default=str(REPO_ROOT / "sgsc_output"))
    parser.add_argument("--models", type=int, default=8)
    parser.add_argument("--runs", type=int, default=3)
    parser.add_argument("--manifest-output", default=str(REPO_ROOT / "sgsc_output" / "sgsc_manifest_v1.json"))
    parser.add_argument("--latex-output", default=str(REPO_ROOT / "paper" / "auto_numbers_sgsc.tex"))
    parser.add_argument("--previous-manifest", default=None)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    sgsc_dir = Path(args.sgsc_dir)
    if not sgsc_dir.is_dir():
        logger.error("SGSC output dir not found: %s", sgsc_dir)
        return 1

    previous = Path(args.previous_manifest) if args.previous_manifest else None

    manifest_dict, report, latex = run_build(sgsc_dir, args.models, args.runs, previous)

    # Write manifest
    manifest_path = Path(args.manifest_output)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest_dict, indent=2, ensure_ascii=False))
    logger.info("Manifest written to %s", manifest_path)

    # Write LaTeX macros
    latex_path = Path(args.latex_output)
    latex_path.parent.mkdir(parents=True, exist_ok=True)
    latex_path.write_text(latex)
    logger.info("LaTeX macros written to %s", latex_path)

    m = report["metrics"]
    print("\n=== Manifest Build ===")
    print(f"Status: {report['status'].upper()}")
    print(f"Guidelines: {m['guidelines_count']}")
    print(f"Scenarios: {m['scenario_count']}")
    print(f"Atoms: {m['total_atoms']}")
    print(f"Episodes: {m['episode_formula']['expected_episodes']}")
    print(f"Artifacts hashed: {m['artifact_count']}")
    print(f"Drift issues: {m['drift_count']}")

    return 1 if report["status"] == "fail" else 0


if __name__ == "__main__":
    sys.exit(main())
