"""α-6 / paper finalization — emit \\providecommand macros for App AY disclosure.

Reads:
  cav_v0_5/cav_v0_5.json
  cav_v0_5/cav_v0_5_dropped.json
  cav_v0_5/03_rxnorm_mapping.json
  reports/path_d_day1/v6_fixed_verdict_matrix.json  (α-6 output, optional)

Writes:
  paper/auto_numbers_cav.tex
    \\providecommand{\\NTotalCav}{1364}
    \\providecommand{\\NExplicit}{1025}
    ... etc.

\\input this in the App AY section of the paper.

anonymous-user provides the α-7 verdict counts via CLI flags (--author-inject,
--extraction-miss, --unclear). If --verdict-matrix is omitted, α-6 macros
are emitted as `??` so the paper still builds with red placeholders.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent.parent


def _load(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _macro_name(placeholder: str) -> str:
    """Convert {SCREAMING_SNAKE} -> CamelCase TeX macro name (with leading 'C')."""
    body = placeholder.strip("{}").lower().split("_")
    return "C" + "".join(part.capitalize() for part in body)


def _fmt_int(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")  # 19,062 -> 19{,}062 for LaTeX


def _fmt_pct(num: float, denom: float) -> str:
    if denom <= 0:
        return "??"
    return f"{(num / denom * 100):.1f}\\%"


def build_macros(
    cav: dict,
    dropped: dict,
    rxnorm: dict,
    verdict: dict | None,
    author_inject: int,
    extraction_miss: int,
    unclear: int,
) -> dict[str, str]:
    s = cav.get("summary", {})
    by_tier = s.get("by_tier", {})

    # CAV side
    macros: dict[str, str] = {
        "{N_TOTAL_CAV}": str(s.get("total_entries", "??")),
        "{N_EXPLICIT}": str(by_tier.get("explicit", "??")),
        "{N_IMPLICIT}": str(by_tier.get("implicit", "??")),
        "{N_EXTENSION}": str(dropped.get("n_dropped", "??")),
    }

    # Extension occurrences (sum)
    drop_entries = dropped.get("dropped_entries", {})
    n_ext_occ = sum(len(e.get("occurrences", [])) for e in drop_entries.values())
    macros["{N_EXTENSION_OCCURRENCES}"] = str(n_ext_occ) if n_ext_occ else "??"

    # RxNorm side
    rxn_md = rxnorm.get("metadata", {})
    n_attempted = rxn_md.get("n_attempted", 0)
    n_matched = rxn_md.get("n_matched", 0)
    macros["{N_MEDICATIONS}"] = str(n_attempted) if n_attempted else "??"
    macros["{N_RXNORM_MATCHED}"] = str(n_matched) if n_matched else "??"
    macros["{RXNORM_MATCH_RATE}"] = f"{(n_matched / n_attempted * 100):.1f}" if n_attempted else "??"

    # α-7 verdict
    macros["{N_AUTHOR_INJECT}"] = str(author_inject)
    macros["{N_EXTRACTION_MISS}"] = str(extraction_miss)
    macros["{N_UNCLEAR}"] = str(unclear)
    macros["{EXTRACTION_MISS_PCT}"] = f"{extraction_miss / 30 * 100:.1f}"

    # α-6 deltas (placeholders if verdict matrix not yet produced)
    if verdict and verdict.get("metadata"):
        md = verdict["metadata"]
        macros["{N_EPISODES}"] = _fmt_int(md.get("n_episodes", 0)) or "??"
    else:
        macros["{N_EPISODES}"] = "19{,}062"  # known from paper

    # Populate strict-FA macros from baseline/full summaries when α-6 has run.
    if verdict and verdict.get("baseline_summary") and verdict.get("full_summary"):
        bs = verdict["baseline_summary"]
        fs = verdict["full_summary"]
        macros["{STRICT_FA_VANILLA}"] = f"{bs['fa_strict_3way']} ({bs['fa_strict_3way_pct']}\\%)"
        macros["{STRICT_FA_FIXED}"] = f"{fs['fa_strict_3way']} ({fs['fa_strict_3way_pct']}\\%)"
        macros["{DELTA_TOTAL}"] = str(fs["fa_strict_3way"] - bs["fa_strict_3way"])

    # Per-source decomposition (CAV / NORM / ENG / ASSESSOR) is deferred to
    # combined-only mode v1; non-timing FA breakdown also deferred.
    for placeholder in [
        "{STRICT_FA_VANILLA}",
        "{STRICT_FA_FIXED}",
        "{N_NONTIMING_VANILLA}",
        "{N_NONTIMING_FIXED}",
        "{DELTA_CAV}",
        "{DELTA_NORM}",
        "{DELTA_ENG}",
        "{DELTA_ASSESSOR}",
        "{DELTA_TOTAL}",
        "{DELTA_CAV_PCT}",
        "{DELTA_NORM_PCT}",
        "{DELTA_ENG_PCT}",
        "{DELTA_ASSESSOR_PCT}",
    ]:
        macros.setdefault(placeholder, "??")

    return macros


def render_tex(macros: dict[str, str], comment_header: str) -> str:
    lines = [
        "% Auto-generated by scripts/cav/generate_macros.py",
        f"% {comment_header}",
        "% Do NOT edit by hand — re-run the generator after CAV / α-6 outputs change.",
        "",
    ]
    for placeholder, value in sorted(macros.items()):
        macro = _macro_name(placeholder)
        lines.append(f"\\providecommand{{\\{macro}}}{{{value}}}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--cav", type=Path, default=REPO_ROOT / "cav_v0_5" / "cav_v0_5.json")
    p.add_argument("--dropped", type=Path, default=REPO_ROOT / "cav_v0_5" / "cav_v0_5_dropped.json")
    p.add_argument("--rxnorm", type=Path, default=REPO_ROOT / "cav_v0_5" / "03_rxnorm_mapping.json")
    p.add_argument(
        "--verdict-matrix",
        type=Path,
        default=REPO_ROOT / "reports" / "path_d_day1" / "v6_fixed_verdict_matrix.json",
        help="α-6 output; if missing, ??-placeholders are emitted.",
    )
    p.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "paper" / "auto_numbers_cav.tex",
    )
    p.add_argument("--author-inject", type=int, required=True, help="α-7 author_inject count")
    p.add_argument("--extraction-miss", type=int, required=True, help="α-7 extraction_miss count")
    p.add_argument("--unclear", type=int, required=True, help="α-7 unclear count")
    args = p.parse_args()

    if (args.author_inject + args.extraction_miss + args.unclear) != 30:
        print(
            f"[ERROR] verdict counts must sum to 30 (got {args.author_inject + args.extraction_miss + args.unclear})",
            file=sys.stderr,
        )
        return 2

    cav = _load(args.cav)
    dropped = _load(args.dropped)
    rxnorm = _load(args.rxnorm)
    verdict = _load(args.verdict_matrix)

    macros = build_macros(
        cav,
        dropped,
        rxnorm,
        verdict,
        args.author_inject,
        args.extraction_miss,
        args.unclear,
    )
    header = (
        f"author_inject={args.author_inject}  extraction_miss={args.extraction_miss}  "
        f"unclear={args.unclear}  alpha6_done={'YES' if verdict else 'NO (?? placeholders)'}"
    )
    tex = render_tex(macros, header)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(tex, encoding="utf-8")
    print(f"[INFO] Wrote {args.output} ({len(macros)} macros)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
