"""Gate 1 E2E harness: real-corpus end-to-end run with structured output buckets.

Wraps ``sgsc.pipeline.run_pipeline`` and produces the 10 artifact paths
required by Gate 1 of the SGSC trust-gate protocol.

Atom bucket semantics (mirrors ``PipelineResult``):
    ``proposed_atoms.json``         input atoms (pre-pipeline)
    ``accepted_atoms.json``         passed grounding + entailment
    ``rejected_atoms.json``         NOT_ENTAILED in at least one field
                                    (firm rejection, Gate 2 mandatory)
    ``review_required_atoms.json``  grounding failure or PARTIAL evidence
                                    under strict mode (needs human triage)

Invariants:
    * accepted ∪ rejected ∪ review_required ⊆ proposed
    * the three pipeline-produced buckets are pairwise disjoint
"""

from __future__ import annotations

from dataclasses import dataclass
import json
import logging
from pathlib import Path
from typing import Any

from sgsc.audit.leakage_scanner import scan_public_scenarios
from sgsc.pipeline import PipelineConfig, run_pipeline
from sgsc.schemas.atom import RecommendationAtom

logger = logging.getLogger(__name__)

_REVIEW_THRESHOLD_DEFAULT = 0.5


# ------------------------------------------------------------------
# Config + Report
# ------------------------------------------------------------------


@dataclass
class E2EHarnessConfig:
    """Configuration for the Gate-1 E2E harness run.

    Attributes:
        corpus_path: Path to a plain-text file containing the full RAG corpus.
        recommendations_path: Path to a JSON file with list of recommendation dicts.
        output_dir: Directory where all 10 output artefacts are written.
        llm_config: AtomProposerConfig passed to the pipeline; ``None`` means
            precomputed atoms must be supplied via ``precomputed_atoms_path``.
        precomputed_atoms_path: Optional path to a JSON file with pre-extracted
            atoms (skips the LLM step).  Required when ``llm_config`` is ``None``.
        max_atoms: Cap on atoms passed to the pipeline (0 = no cap).
        grounding_threshold: Quote-grounding similarity threshold forwarded to
            the pipeline.
        entailment_mode: Entailment checker mode forwarded to the pipeline.
        guideline_id: Guideline identifier forwarded to the pipeline.
        guideline_name: Human-readable guideline name forwarded to the pipeline.
    """

    corpus_path: str
    recommendations_path: str
    output_dir: str
    llm_config: Any | None = None
    precomputed_atoms_path: str | None = None
    max_atoms: int = 0
    grounding_threshold: float = 0.4
    entailment_mode: str = "rule_based"
    guideline_id: str = "sgsc_harness"
    guideline_name: str = "SGSC Harness Run"


@dataclass
class E2EHarnessReport:
    """Paths to all Gate-1 output artefacts.

    Every field is an absolute path string to a JSON file written by the
    harness.  All files are guaranteed to exist and contain valid JSON when
    ``run_e2e_harness`` returns successfully.

    Attributes:
        proposed_atoms_path: All atoms before any pipeline filtering.
        accepted_atoms_path: Atoms that passed grounding + entailment.
        rejected_atoms_path: Atoms with NOT_ENTAILED in at least one field
            (firm rejection per Gate 2 mandatory entailment).
        review_required_atoms_path: Atoms that need human triage —
            grounding failures or PARTIAL evidence under strict mode.
        constraints_path: Derived constraints compiled from accepted atoms.
        seeds_path: Scenario seeds generated by the pipeline.
        scenarios_public_path: Public (agent-visible) scenario split.
        scenarios_private_path: Private (scorer-only) scenario split.
        coverage_report_path: JSON coverage report from the pipeline.
        leakage_report_path: Leakage audit report for the public scenarios.
    """

    proposed_atoms_path: str = ""
    accepted_atoms_path: str = ""
    rejected_atoms_path: str = ""
    review_required_atoms_path: str = ""
    constraints_path: str = ""
    seeds_path: str = ""
    scenarios_public_path: str = ""
    scenarios_private_path: str = ""
    coverage_report_path: str = ""
    leakage_report_path: str = ""


# ------------------------------------------------------------------
# Internal helpers
# ------------------------------------------------------------------


def _load_corpus(path: str) -> str:
    """Load corpus text from a plain-text file."""
    return Path(path).read_text(encoding="utf-8")


def _load_recommendations(path: str) -> list[dict[str, Any]]:
    """Load recommendation list from a JSON file."""
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _load_precomputed_atoms(path: str, max_atoms: int) -> list[RecommendationAtom]:
    """Load pre-extracted atoms from a JSON file and optionally cap count."""
    raw: list[dict[str, Any]] = json.loads(Path(path).read_text(encoding="utf-8"))
    atoms = [RecommendationAtom.model_validate(a) for a in raw]
    if max_atoms > 0:
        atoms = atoms[:max_atoms]
    return atoms


def _write_json(path: Path, data: Any) -> str:
    """Serialise *data* to *path* and return the path string."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return str(path)


def _atoms_to_json_list(atoms: list[RecommendationAtom]) -> list[dict[str, Any]]:
    """Convert atoms to JSON-serialisable dicts."""
    return [a.model_dump() for a in atoms]


def _build_leakage_report(
    scenarios_public: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    """Run the public-scenario leakage scan and return a JSON-able dict."""
    result = scan_public_scenarios(scenarios_public)
    return {
        "passed": result.passed,
        "scenarios_scanned": result.scenarios_scanned,
        "leaks": result.leaks,
    }


# ------------------------------------------------------------------
# Main entry point
# ------------------------------------------------------------------


def run_e2e_harness(config: E2EHarnessConfig) -> E2EHarnessReport:
    """Run the full SGSC pipeline end-to-end and emit the Gate-1 artefacts.

    Args:
        config: Harness configuration (see ``E2EHarnessConfig``).

    Returns:
        ``E2EHarnessReport`` with paths to all 10 output artefacts.

    Raises:
        ValueError: When neither ``llm_config`` nor ``precomputed_atoms_path``
            is provided.
        FileNotFoundError: When a required input path does not exist.
    """
    if config.llm_config is None and config.precomputed_atoms_path is None:
        raise ValueError("Either llm_config or precomputed_atoms_path must be provided.")

    out = Path(config.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    corpus_text = _load_corpus(config.corpus_path)
    recommendations = _load_recommendations(config.recommendations_path)

    precomputed: list[RecommendationAtom] | None = None
    if config.precomputed_atoms_path:
        precomputed = _load_precomputed_atoms(
            config.precomputed_atoms_path, config.max_atoms
        )

    # Save proposed atoms BEFORE pipeline (pre-filter snapshot)
    proposed = list(precomputed) if precomputed else []
    proposed_path = _write_json(
        out / "atoms_proposed.json", _atoms_to_json_list(proposed)
    )
    logger.info("Saved %d proposed atoms -> %s", len(proposed), proposed_path)

    pipeline_cfg = PipelineConfig(
        guideline_id=config.guideline_id,
        guideline_name=config.guideline_name,
        output_dir=str(out),
        llm_config=config.llm_config,
        entailment_mode=config.entailment_mode,
        grounding_threshold=config.grounding_threshold,
    )

    pipeline_result = run_pipeline(
        pipeline_cfg,
        corpus_full_text=corpus_text,
        recommendations=recommendations,
        precomputed_atoms=precomputed,
    )

    accepted = pipeline_result.atoms
    accepted_path = _write_json(
        out / "atoms_accepted.json", _atoms_to_json_list(accepted)
    )

    # Rejected bucket: atoms with NOT_ENTAILED in at least one field
    # (firm rejection per Gate 2). Sourced directly from the pipeline.
    rejected = pipeline_result.rejected_atoms
    rejected_path = _write_json(
        out / "atoms_rejected.json", _atoms_to_json_list(rejected)
    )

    # Review-required bucket: grounding failures + PARTIAL-evidence atoms
    # (under strict mode). Sourced directly from the pipeline. Fall back to
    # "proposed minus accepted minus rejected" if the pipeline did not surface
    # them (older callers that pre-date the rejected/review split).
    if pipeline_result.review_required_atoms:
        review_required = pipeline_result.review_required_atoms
    else:
        accepted_ids = {a.atom_id for a in accepted}
        rejected_ids = {a.atom_id for a in rejected}
        review_required = [
            a
            for a in proposed
            if a.atom_id not in accepted_ids and a.atom_id not in rejected_ids
        ]
    review_path = _write_json(
        out / "atoms_review_required.json", _atoms_to_json_list(review_required)
    )

    # Seeds: derive from pipeline graph + seeds (pipeline writes its own files;
    # we write an additional harness-level summary)
    seeds_data = {
        "total_seeds": pipeline_result.total_seeds,
        "total_families": pipeline_result.total_families,
        "total_mutations": pipeline_result.total_mutations,
    }
    seeds_path = _write_json(out / "seeds_summary.json", seeds_data)

    # Constraints: pipeline already wrote {guideline_id}_constraints.json;
    # record its path in the report
    constraints_path = str(out / f"{config.guideline_id}_constraints.json")

    # Public / private scenario paths (written by pipeline)
    public_path = str(out / f"{config.guideline_id}_scenarios_public.json")
    private_path = str(out / f"{config.guideline_id}_scenarios_private.json")

    # Coverage report path (pipeline writes JSON under coverage_paths)
    coverage_path = pipeline_result.coverage_paths.get("json", "")

    # Leakage report
    leakage_data = _build_leakage_report(pipeline_result.scenarios_public)
    leakage_path = _write_json(out / "leakage_report.json", leakage_data)

    logger.info(
        "Harness complete: %d accepted, %d review_required, leakage_passed=%s",
        len(accepted),
        len(review_required),
        leakage_data["passed"],
    )

    return E2EHarnessReport(
        proposed_atoms_path=proposed_path,
        accepted_atoms_path=accepted_path,
        rejected_atoms_path=rejected_path,
        review_required_atoms_path=review_path,
        constraints_path=constraints_path,
        seeds_path=seeds_path,
        scenarios_public_path=public_path,
        scenarios_private_path=private_path,
        coverage_report_path=coverage_path,
        leakage_report_path=leakage_path,
    )
